### ISSUE TITLE
gRPC Error (Quota exceeded)

### ISSUE THREAD

**Issue by tvolkert** [flutter/cocoon#412]
```
$ curl -i "https://flutter-dashboard.appspot.com/api/public/build-status"
HTTP/2 500 
date: Thu, 12 Sep 2019 03:17:12 GMT
content-type: text/plain; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
via: 1.1 google
alt-svc: quic=":443"; ma=2592000; v="46,43,39"

gRPC Error (8, Quota exceeded.)
#0      GrpcDatastoreImpl.query (package:appengine/src/grpc_api_impl/datastore_impl.dart:258:41)
<asynchronous suspension>
#1      Query.run.<anonymous closure> (package:gcloud/src/db/db.dart:246:12)
#2      StreamFromPages._onListen (package:gcloud/common.dart:72:5)
#3      _runGuarded (dart:async/stream_controller.dart:805:24)
#4      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:684:7)
#5      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:414:13)
#6      _StreamController._subscribe (dart:async/stream_controller.dart:683:18)
#7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#8      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:123:10)
#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:91:16)
#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:86:12)
#12     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1004:30)
#13     _StreamIterator.moveNext (dart:async/stream_impl.dart:991:12)
#14     DatastoreService.queryTasksGroupedByStage (package:cocoon_service/src/service/datastore.dart)
<asynchronous suspension>
#15     BuildStatusProvider.retrieveCommitStatus (package:cocoon_service/src/service/build_status_provider.dart:68:50)
<asynchronous suspension>
#16     BuildStatusProvider.calculateCumulativeStatus (package:cocoon_service/src/service/build_status_provider.dart:32:39)
<asynchronous suspension>
#17     GetBuildStatus.get (package:cocoon_service/src/request_handlers/get_build_status.dart:32:58)
<asynchronous suspension>
#18     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#24     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:61:23)
<asynchronous suspension>
#25     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#26     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:18)
#27     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1500:12)
#32     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#33     fork (package:gcloud/service_scope.dart:104:30)
#34     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:55:9)
#35     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#42     _StreamController._add (dart:async/stream_controller.dart:640:7)
#43     _StreamController.add (dart:async/stream_controller.dart:586:5)
#44     _HttpServer._handleRequest (dart:_http/http_impl.dart:2670:19)
#45     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2428:19)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     _HttpParser._headersEnd (dart:_http/http_parser.dart:372:19)
#55     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)
#56     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#57     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#58     _rootRunUnary (dart:async/zone.dart:1132:38)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#63     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#64     _StreamController._add (dart:async/stream_controller.dart:640:7)
#65     _StreamController.add (dart:async/stream_controller.dart:586:5)
#66     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#67     _rootRunUnary (dart:async/zone.dart:1136:13)
#68     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#69     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#70     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#71     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#72     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#73     _StreamController._add (dart:async/stream_controller.dart:640:7)
#74     _StreamController.add (dart:async/stream_controller.dart:586:5)
#75     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#76     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#77     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#78     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#79     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#80     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by escamoteur** [comment]
Is this related to https://github.com/flutter/flutter/issues/41667

**Comment by tvolkert** [comment]
Yep - closing as a dup
